- name: Copy setting files
  file:
    src:  ~/dev/src/github.com/shimbaco/devenv/application_support/Code/User/{{ item }}
    path: ~/Library/Application Support/Code/User/{{ item }}
    state: link
  with_items:
    - keybindings.json
    - locale.json
    - settings.json

- name: Copy setting directories
  command: ln -nfs ~/dev/src/github.com/shimbaco/devenv/dotfiles/{{ item }} ~/
  with_items:
    - .vscode
