- name: 設定ファイルを配置する
  copy:
    src:  ~/dev/devenv/dotfiles/{{ item }}
    dest: ~/{{ item }}
  with_items:
    - .atom/
    - .ackrc
    - .aliases
    - .ctags
    - .gemrc
    - .gitconfig
    - .gitignore_global
    - .gvimrc
    - .pryrc
    - .railsrc
    - .spring.rb
    - .tmux.conf
    - .vim/
    - .vimrc
    - .zlogin
    - .zsh/
    - .zshrc
    - bin/

- name: sshmに実行権限を与える
  file:
    path: ~/bin/sshm
    mode: 0755
