- name: 設定ファイルを配置する
  file:
    src:  ~/dev/src/github.com/shimbaco/devenv/dotfiles/{{ item }}
    path: ~/{{ item }}
    state: link
  with_items:
    - .aliases
    - .gemrc
    - .gitconfig
    - .gitignore_global
    - .gvimrc
    - .pryrc
    - .railsrc
    - .vimrc
    - .zlogin
    - .zshrc

- name: 設定ファイルを配置する (ディレクトリ)
  command: ln -nfs ~/dev/src/github.com/shimbaco/devenv/dotfiles/{{ item }} ~/
  with_items:
    - .bundle
    - .vim
    - .zsh
    - bin

- name: ~/bin以下のファイルに実行権限を与える
  file:
    path: ~/bin/{{ item }}
    mode: 0755
  with_items:
    - bof
    - sshm
