- name: Homebrewをアップデート
  homebrew:
    update_homebrew: yes

- name: Homebrewのtapリポジトリを追加
  homebrew_tap:
    tap: '{{ item }}'
    state: present
  with_items:
    - heroku/brew # Heroku CLIをインストールするときに必要