- name: rbenvがインストールされているか確認する
  command:       test -x ~/.rbenv
  register:      rbenv_present
  ignore_errors: yes

- name: rbenvをダウンロードする
  git:
    repo:           git://github.com/sstephenson/rbenv.git
    accept_hostkey: yes
    dest:           ~/.rbenv
  when: rbenv_present|failed

- name: ruby-buildがインストールされているか確認する
  command:       test -x ~/.rbenv/plugins/ruby-build
  register:      rbuild_present
  ignore_errors: yes

- name: ruby-buildをダウンロードする
  git:
    repo: git://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
  when: rbuild_present|failed

- name: Rubyがインストールされているか確認する
  shell:         ~/.rbenv/bin/rbenv versions | grep {{ ruby_version }}
  register:      ruby_installed
  ignore_errors: yes

- name: Rubyをインストールする
  shell: ~/.rbenv/bin/rbenv install {{ ruby_version }}
  when:  ruby_installed|failed

- name: インストールしたRubyをシステム全体で使用する
  shell: ~/.rbenv/bin/rbenv global {{ ruby_version }}
  when:  ruby_installed|failed

- name: rehash
  shell: ~/.rbenv/bin/rbenv rehash
  when:  ruby_installed|failed

- name: Bundlerをインストールする
  shell: ~/.rbenv/bin/rbenv exec gem install bundle --no-ri --no-rdoc

- name: Foremanをインストールする
  shell: ~/.rbenv/bin/rbenv exec gem install foreman --no-ri --no-rdoc
