- hosts: localhost
  # 対象ホストの情報を取得しない
  # (取得しないことで実行時間が短縮されるらしい)
  gather_facts: no
  connection: local
  roles:
    - basic
    - dotfiles
    # - ssh
    - homebrew
    - heroku
    - peco

    # - asdf
    # - atom
    # - aws
    # - ctags
    # - direnv
    # - dropbox
    # - elixir
    # - ghq
    # - go
    # - graphiql
    # - hub
    # - hyperterm
    # - imagemagick
    # - insomnia
    # - mercurial
    # - mongodb
    # - mysql
    # - nodejs
    # - phantomjs
    # - postgresql
    # - redis
    # - ruby
    # - zsh
