- hosts: localhost
  # 対象ホストの情報を取得しない
  # (取得しないことで実行時間が短縮されるらしい)
  gather_facts: no
  connection: local
  roles:
    - basic
    - dotfiles
    - ssh
    - homebrew
    - direnv
    - heroku
    - asdf
    - ruby
    - nodejs
    - postgresql
    - peco
    - aws
    - graphiql

    # - atom
    # - ctags
    # - dropbox
    # - elixir
    # - ghq
    # - go
    # - hub
    # - hyperterm
    # - imagemagick
    # - insomnia
    # - mercurial
    # - mongodb
    # - mysql
    # - phantomjs
    # - redis
    # - zsh
